openapi: "3.0.0"
info:
    description: |
        API documentation for talk on subject "Schema validation meets functional testing"
    version: "1.0.0"
    title: Schema validation meets functional testing
paths:
    /api/v1/common/pokedex-entries:
        $ref: './Pokedex/PokedexEntries.yaml'
    /api/v1/common/pokedex-entries/{id}:
        $ref: './Pokedex/PokedexEntryById.yaml'
